const data = [
    { id: 1, name: 'Iphone 2G', armazenamento: "16GB", ram: '128MB', processador: "ARM 11", tela: "TFT LCD" },
    { id: 2, name: 'iPhone 3G', armazenamento: "16GB", ram: '128MB', processador: "ARM 11", tela: "TFT LCD" },
    { id: 3, name: 'iPhone 3G S', armazenamento: "32GB", ram: '256MB', processador: "ARM Cortex A8", tela: "TFT LCD" },
    { id: 4, name: 'iPhone 4', armazenamento: "32GB", ram: '512MB', processador: "ARM Apple A4", tela: "TFT LCD" },
    { id: 5, name: 'iPhone 4S', armazenamento: "64GB", ram: '512MB', processador: "Apple A5", tela: "IPS LCD" },
    { id: 6, name: 'iPhone 5', armazenamento: "64GB", ram: '1GB', processador: "Apple A6", tela: "IPS LCD" },
    { id: 7, name: 'iPhone 5S', armazenamento: "64GB", ram: '1GB', processador: "Cyclone Apple A7", tela: "IPS LCD" },
    { id: 8, name: 'iPhone 5C', armazenamento: "8GB", ram: '1GB', processador: "Apple A6", tela: "IPS LCD" },
    { id: 9, name: 'iPhone 6', armazenamento: "128GB", ram: '1GB', processador: "Apple A8", tela: "IPS LCD" },
    { id: 10, name: 'iPhone 6 Plus', armazenamento: "128GB", ram: '1GB', processador: "Apple A8", tela: "IPS LCD" },
    { id: 11, name: 'iPhone 6S', armazenamento: "128GB", ram: '2GB', processador: "Apple A9", tela: "IPS LCD" },
    { id: 12, name: 'iPhone 6S Plus', armazenamento: "128GB", ram: '2GB', processador: "Apple A9", tela: "IPS LCD" },
    { id: 13, name: 'iPhone SE 2016', armazenamento: "64GB", ram: '2GB', processador: "Twister Apple A9", tela: "IPS LCD" },
    { id: 14, name: 'iPhone 7', armazenamento: "256GB", ram: '2GB', processador: "Apple A10 Fusion", tela: "IPS LCD" },
    { id: 15, name: 'iPhone 7 Plus', armazenamento: "32GB", ram: '3GB', processador: "Quad Core Apple A10 Fusion", tela: "IPS LCD" },
    { id: 16, name: 'iPhone 8', armazenamento: "256GB", ram: '2GB', processador: "Apple A11 Bionic", tela: "IPS LCD" },
    { id: 17, name: 'iPhone 8 Plus', armazenamento: "256GB", ram: '3GB', processador: "Apple A11 Bionic", tela: "IPS LCD" },
    { id: 19, name: 'iPhone X', armazenamento: "256GB", ram: '3GB', processador: "Apple A11 Bionic", tela: "OLED" },
    { id: 20, name: 'iPhone XS', armazenamento: "512GB", ram: '4GB', processador: "Apple A12 Bionic", tela: "OLED" },
    { id: 21, name: 'iPhone XR', armazenamento: "256GB", ram: '3GB', processador: "Apple A12 Bionic", tela: "IPS LCD" },
    { id: 22, name: 'iPhone XS Max', armazenamento: "512GB", ram: '4GB', processador: "Apple A12 Bionic", tela: "OLED" },
    { id: 23, name: 'iPhone 11', armazenamento: "512GB", ram: '4GB', processador: "Apple A13 Bionic", tela: "LCD" },
    { id: 24, name: 'iPhone 11 Pro', armazenamento: "512GB", ram: '4GB', processador: "Apple A13 Bionic", tela: "OLED" },
    { id: 25, name: 'iPhone 11 Pro Max', armazenamento: "512GB", ram: '4GB', processador: "Apple A13 Bionic", tela: "OLED" },
    { id: 26, name: 'iPhone SE 2020', armazenamento: "256GB", ram: '3GB', processador: "Apple A13 Bionic", tela: "IPS LCD" },
    { id: 27, name: 'iPhone 12 Mini', armazenamento: "256GB", ram: '4GB', processador: "Apple A14 Bionic", tela: "Super Retina XDR OLED" },
    { id: 28, name: 'iPhone 12', armazenamento: "256GB", ram: '4GB', processador: "Apple A14 Bionic", tela: "Super Retina XDR OLED" },
    { id: 29, name: 'iPhone 12 Pro', armazenamento: "512GB", ram: '6GB', processador: "Apple A14 Bionic", tela: "Super Retina XDR OLED" },
    { id: 30, name: 'iPhone 12 Pro Max', armazenamento: "512GB", ram: '6GB', processador: "Apple A14 Bionic", tela: "Super Retina XDR OLED" },
    { id: 31, name: 'iPhone 13 Mini', armazenamento: "512GB", ram: '4GB', processador: "Apple A15 Bionic", tela: "Super Retina XDR OLED" },
    { id: 32, name: 'iPhone 13', armazenamento: "512GB", ram: '4GB', processador: "Apple A15 Bionic", tela: "Super Retina XDR OLED" },
    { id: 33, name: 'iPhone 13 Pro', armazenamento: "1000GB", ram: '6GB', processador: "Apple A15 Bionic", tela: "Super Retina XDR OLED" },
    { id: 34, name: 'iPhone 13 Pro Max', armazenamento: "1000GB", ram: '6GB', processador: "Apple A15 Bionic", tela: "Super Retina XDR OLED" },
    { id: 35, name: 'iPhone SE', armazenamento: "256GB", ram: '3GB', processador: "Apple A15 Bionic", tela: "Retina IPS LCD" },
    { id: 36, name: 'Samsung Galaxy S', armazenamento: "16GB", ram: '512MB', processador: "Cortex A8 ARM Hummingbird", tela: "Super AMOLED" },
    { id: 37, name: 'Samsung Galaxy Beam I8520', armazenamento: "384MB", ram: '384MB', processador: "720 MHz", tela: "Super AMOLED" },
    { id: 38, name: 'Samsung Galaxy S2', armazenamento: "16GB", ram: '1GB', processador: "ARM Cortex A9", tela: "Super AMOLED Plus" },
    { id: 39, name: 'Samsung i9003 Galaxy SL', armazenamento: "16GB", ram: '478MB', processador: "Cortex A8", tela: "Super Clear LCD" },
    { id: 40, name: 'Samsung Galaxy Z', armazenamento: "8GB", ram: '1GB', processador: "NVDIA Tegra 2 AP20H Dual Core", tela: "Super Clear LCD" },
    { id: 41, name: 'Samsung Nexus S', armazenamento: "16GB", ram: '512MB', processador: "Cortex A8 SAMSUNG Hummingbird", tela: "Super AMOLED" },
    { id: 42, name: 'Samsung Galaxy S2 LTE', armazenamento: "16GB", ram: '1GB', processador: "SAMSUNG", tela: "Super AMOLED Plus" },
    { id: 43, name: 'Samsung Galaxy Y', armazenamento: "160MB", ram: '290MB', processador: "Broadcom BCM21553", tela: "TFT LCD" },
    { id: 44, name: 'Samsung Galaxy Nexus', armazenamento: "16GB", ram: '1GB', processador: "Cortex-A9 Texas Instruments OMAP 4460", tela: "Super AMOLED" },
    { id: 45, name: 'Samsung Galaxy Y Duos', armazenamento: "512MB", ram: '290MB', processador: "Broadcom BCM21553", tela: "TFT LCD" },
    { id: 46, name: 'Samsung Galaxy Ace Plus', armazenamento: "3GB", ram: '512MB', processador: "Adreno 200", tela: "TFT LCD" },
    { id: 47, name: 'Samsung Galaxy W', armazenamento: "2GB", ram: '512MB', processador: "Snapdragon Qualcomm MSM8255T", tela: "TFT LCD" },
    { id: 48, name: 'Samsung Galaxy Ace 2', armazenamento: "4GB", ram: '768MB', processador: "SAMSUNG", tela: "PLS LCD" },

  ];
    
  module.exports = data;  