const data = [
    { id: 1, name: 'Iphone 2G', armazenamento: "16GB", ram: '128MB', processador: "ARM 11", tela: "TFT LCD" },
    { id: 2, name: 'iPhone 3G', armazenamento: "16GB", ram: '128MB', processador: "ARM 11", tela: "TFT LCD" },
    { id: 3, name: 'iPhone 3G S', armazenamento: "32GB", ram: '256MB', processador: "ARM Cortex A8", tela: "TFT LCD" },
    { id: 4, name: 'iPhone 4', armazenamento: "32GB", ram: '512MB', processador: "ARM Apple A4", tela: "TFT LCD" },
    { id: 5, name: 'iPhone 4S', armazenamento: "64GB", ram: '512MB', processador: "Apple A5", tela: "IPS LCD" },
    { id: 6, name: 'iPhone 5', armazenamento: "64GB", ram: '1GB', processador: "Apple A6", tela: "IPS LCD" },
    { id: 7, name: 'iPhone 5S', armazenamento: "64GB", ram: '1GB', processador: "Cyclone Apple A7", tela: "IPS LCD" },
    { id: 8, name: 'iPhone 5C', armazenamento: "8GB", ram: '1GB', processador: "Apple A6", tela: "IPS LCD" },
    { id: 9, name: 'iPhone 6', armazenamento: "128GB", ram: '1GB', processador: "Apple A8", tela: "IPS LCD" },
    { id: 10, name: 'iPhone 6 Plus', armazenamento: "128GB", ram: '1GB', processador: "Apple A8", tela: "IPS LCD" },
    { id: 11, name: 'iPhone 6S', armazenamento: "128GB", ram: '2GB', processador: "Apple A9", tela: "IPS LCD" },
    { id: 12, name: 'iPhone 6S Plus', armazenamento: "128GB", ram: '2GB', processador: "Apple A9", tela: "IPS LCD" },
    { id: 13, name: 'iPhone SE 2016', armazenamento: "64GB", ram: '2GB', processador: "Twister Apple A9", tela: "IPS LCD" },
    { id: 14, name: 'iPhone 7', armazenamento: "256GB", ram: '2GB', processador: "Apple A10 Fusion", tela: "IPS LCD" },
    { id: 15, name: 'iPhone 7 Plus', armazenamento: "32GB", ram: '3GB', processador: "Quad Core Apple A10 Fusion", tela: "IPS LCD" },
    { id: 16, name: 'iPhone 8', armazenamento: "256GB", ram: '2GB', processador: "Apple A11 Bionic", tela: "IPS LCD" },
    { id: 17, name: 'iPhone 8 Plus', armazenamento: "256GB", ram: '3GB', processador: "Apple A11 Bionic", tela: "IPS LCD" },
    { id: 19, name: 'iPhone X', armazenamento: "256GB", ram: '3GB', processador: "Apple A11 Bionic", tela: "OLED" },
    { id: 20, name: 'iPhone XS', armazenamento: "512GB", ram: '4GB', processador: "Apple A12 Bionic", tela: "OLED" },
    { id: 21, name: 'iPhone XR', armazenamento: "256GB", ram: '3GB', processador: "Apple A12 Bionic", tela: "IPS LCD" },
    { id: 22, name: 'iPhone XS Max', armazenamento: "512GB", ram: '4GB', processador: "Apple A12 Bionic", tela: "OLED" },
    { id: 23, name: 'iPhone 11', armazenamento: "512GB", ram: '4GB', processador: "Apple A13 Bionic", tela: "LCD" },
    { id: 24, name: 'iPhone 11 Pro', armazenamento: "512GB", ram: '4GB', processador: "Apple A13 Bionic", tela: "OLED" },
    { id: 25, name: 'iPhone 11 Pro Max', armazenamento: "512GB", ram: '4GB', processador: "Apple A13 Bionic", tela: "OLED" },
    { id: 26, name: 'iPhone SE 2020', armazenamento: "256GB", ram: '3GB', processador: "Apple A13 Bionic", tela: "IPS LCD" },
    { id: 27, name: 'iPhone 12 Mini', armazenamento: "256GB", ram: '4GB', processador: "Apple A14 Bionic", tela: "Super Retina XDR OLED" },
    { id: 28, name: 'iPhone 12', armazenamento: "256GB", ram: '4GB', processador: "Apple A14 Bionic", tela: "Super Retina XDR OLED" },
    { id: 29, name: 'iPhone 12 Pro', armazenamento: "512GB", ram: '6GB', processador: "Apple A14 Bionic", tela: "Super Retina XDR OLED" },
    { id: 30, name: 'iPhone 12 Pro Max', armazenamento: "512GB", ram: '6GB', processador: "Apple A14 Bionic", tela: "Super Retina XDR OLED" },
    { id: 31, name: 'iPhone 13 Mini', armazenamento: "512GB", ram: '4GB', processador: "Apple A15 Bionic", tela: "Super Retina XDR OLED" },
    { id: 32, name: 'iPhone 13', armazenamento: "512GB", ram: '4GB', processador: "Apple A15 Bionic", tela: "Super Retina XDR OLED" },
    { id: 33, name: 'iPhone 13 Pro', armazenamento: "1000GB", ram: '6GB', processador: "Apple A15 Bionic", tela: "Super Retina XDR OLED" },
    { id: 34, name: 'iPhone 13 Pro Max', armazenamento: "1000GB", ram: '6GB', processador: "Apple A15 Bionic", tela: "Super Retina XDR OLED" },
    { id: 35, name: 'iPhone SE', armazenamento: "256GB", ram: '3GB', processador: "Apple A15 Bionic", tela: "Retina IPS LCD" },
    { id: 36, name: 'Samsung Galaxy S', armazenamento: "16GB", ram: '512MB', processador: "Cortex A8 ARM Hummingbird", tela: "Super AMOLED" },
    { id: 37, name: 'Samsung Galaxy Beam I8520', armazenamento: "384MB", ram: '384MB', processador: "720 MHz", tela: "Super AMOLED" },
    { id: 38, name: 'Samsung Galaxy S2', armazenamento: "16GB", ram: '1GB', processador: "ARM Cortex A9", tela: "Super AMOLED Plus" },
    { id: 39, name: 'Samsung i9003 Galaxy SL', armazenamento: "16GB", ram: '478MB', processador: "Cortex A8", tela: "Super Clear LCD" },
    { id: 40, name: 'Samsung Galaxy Z', armazenamento: "8GB", ram: '1GB', processador: "NVDIA Tegra 2 AP20H Dual Core", tela: "Super Clear LCD" },
    { id: 41, name: 'Samsung Nexus S', armazenamento: "16GB", ram: '512MB', processador: "Cortex A8 SAMSUNG Hummingbird", tela: "Super AMOLED" },
    { id: 42, name: 'Samsung Galaxy S2 LTE', armazenamento: "16GB", ram: '1GB', processador: "SAMSUNG", tela: "Super AMOLED Plus" },
    { id: 43, name: 'Samsung Galaxy Y', armazenamento: "160MB", ram: '290MB', processador: "Broadcom BCM21553", tela: "TFT LCD" },
    { id: 44, name: 'Samsung Galaxy Nexus', armazenamento: "16GB", ram: '1GB', processador: "Cortex-A9 Texas Instruments OMAP 4460", tela: "Super AMOLED" },
    { id: 45, name: 'Samsung Galaxy Y Duos', armazenamento: "512MB", ram: '290MB', processador: "Broadcom BCM21553", tela: "TFT LCD" },
    { id: 46, name: 'Samsung Galaxy Ace Plus', armazenamento: "3GB", ram: '512MB', processador: "Adreno 200", tela: "TFT LCD" },
    { id: 47, name: 'Samsung Galaxy W', armazenamento: "2GB", ram: '512MB', processador: "Snapdragon Qualcomm MSM8255T", tela: "TFT LCD" },
    { id: 48, name: 'Samsung Galaxy Ace 2', armazenamento: "4GB", ram: '768MB', processador: "SAMSUNG", tela: "PLS LCD" },
    { id: 49, name: 'Samsung Galaxy mini 2', armazenamento: "4GB", ram: '512MB', processador: "Qualcomm MSM7227", tela: "TFT LCD" },
    { id: 50, name: 'Samsung Galaxy Beam I8530', armazenamento: "8GB", ram: '768MB', processador: "ARM Cortex A9", tela: "TFT LCD" },
    { id: 51, name: 'Samsung Galaxy S3', armazenamento: "16GB", ram: '1GB', processador: "SAMSUNG Exynos 4412", tela: "Super AMOLED" },
    { id: 52, name: 'Samsung Galaxy S2 Lite', armazenamento: "8GB", ram: '768MB', processador: "SAMSUNG", tela: "Super AMOLED" },
    { id: 53, name: 'Samsung Galaxy S Duos S7562', armazenamento: "4GB", ram: '768MB', processador: "Snapdragon Qualcomm MSM7227A", tela: "TFT LCD" },
    { id: 54, name: 'Samsung Galaxy Note 2', armazenamento: "32GB", ram: '2GB', processador: "Cortex-A9 SAMSUNG Exynos 4412", tela: "Super AMOLED" },
    { id: 55, name: 'Samsung Galaxy X', armazenamento: "16GB", ram: '1GB', processador: "Texas Instruments OMAP4460", tela: "Super AMOLED" },
    { id: 56, name: 'Samsung Galaxy Music', armazenamento: "4GB", ram: '512MB', processador: "A9", tela: "TFT LCD" },
    { id: 57, name: 'Samsung Galaxy Music Duos', armazenamento: "4GB", ram: '512MB', processador: "A9", tela: "TFT LCD" },
    { id: 58, name: 'Samsung Galaxy S3 Mini', armazenamento: "8GB", ram: '1GB', processador: "NovaThor U8420", tela: "Super AMOLED" },
    { id: 59, name: 'Samsung Galaxy Premier', armazenamento: "16GB", ram: '1GB', processador: "Texas Instruments OMAP 4470", tela: "Super AMOLED" },
    { id: 60, name: 'Samsung Galaxy Gran Duos', armazenamento: "8GB", ram: '1GB', processador: "Cortex-A9 Broadcom BCM28155", tela: "TFT LCD" },
    { id: 61, name: 'Samsung Galaxy S2 Plus', armazenamento: "8GB", ram: '1GB', processador: "ARM Cortex A9", tela: "Super AMOLED Plus" },
    { id: 62, name: 'Samsung Galaxy Xcover 2', armazenamento: "4GB", ram: '1GB', processador: "Cortex-A9 ST Ericsson NovaThor U8500", tela: "TFT LCD" },
    { id: 63, name: 'Samsung Galaxy Express', armazenamento: "8GB", ram: '1GB', processador: "Adreno 225", tela: "Super AMOLED Plus" },
    { id: 64, name: 'Samsung Galaxy Young', armazenamento: "4GB", ram: '768MB', processador: "Cortex A5 Qualcomm Snapdragon MSM7227A", tela: "TFT LCD" },
    { id: 65, name: 'Samsung Galaxy S4 I9500', armazenamento: "32GB", ram: '2GB', processador: "SAMSUNG Exynos 5 Octa 5410", tela: "Super AMOLED" },
    { id: 66, name: 'Samsung Galaxy S4 Mini', armazenamento: "8GB", ram: '1.5GB', processador: "Snapdragon 400 Qualcomm MSM8930", tela: "Super AMOLED" },
    { id: 67, name: 'Samsung Galaxy Win', armazenamento: "8GB", ram: '1GB', processador: "Snapdragon 200 Qualcomm MSM8225Q", tela: "TFT LCD" },
    { id: 68, name: 'Samsung Galaxy S4 I9505', armazenamento: "16GB", ram: '2GB', processador: "Snapdragon 600 Qualcomm APQ8064T", tela: "Super AMOLED" },
    { id: 69, name: 'Samsung Galaxy Note 8.0', armazenamento: "32GB", ram: '2GB', processador: "Cortex-A9 Exynos 4412", tela: "TFT LCD" },
    { id: 70, name: 'Samsung Galaxy S4 Active', armazenamento: "16GB", ram: '2GB', processador: "Snapdragon 600 Qualcomm APQ8064T", tela: "TFT LCD" },
    { id: 71, name: 'Samsung Galaxy S4 Zoom', armazenamento: "8GB", ram: '1.5GB', processador: "Cortex-A9 SAMSUNG Exynos 4212", tela: "Super AMOLED" },
    { id: 72, name: 'Samsung Galaxy Note 3', armazenamento: "32GB", ram: '3GB', processador: "Snapdragon 800 Qualcomm MSM8974", tela: "Super AMOLED" },
    { id: 73, name: 'Samsung Galaxy S Plus', armazenamento: "16GB", ram: '512MB', processador: "Snapdragon Qualcomm MSM8255T", tela: "Super AMOLED" },
    { id: 74, name: 'Samsung Galaxy Gran 2', armazenamento: "8GB", ram: '1.5GB', processador: "Cortex-A7 Qualcomm Snapdragon 400 MSM8226", tela: "TFT LCD" },
    { id: 75, name: 'Samsung Galaxy S Duos 2', armazenamento: "4GB", ram: '768MB', processador: "Cortex-A9", tela: "TFT LCD" },
    { id: 76, name: 'Samsung Galaxy J', armazenamento: "16GB", ram: '3GB', processador: "Snapdragon 800 Qualcomm MSM8974", tela: "Super AMOLED" },
    { id: 77, name: 'Samsung Galaxy Gran Neo', armazenamento: "8GB", ram: '1GB', processador: "Cortex-A7 Broadcom BCM23550", tela: "TFT LCD" },
    { id: 78, name: 'Samsung Galaxy Note 3 Neo Duos', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A7 Qualcomm MSM8228", tela: "Super AMOLED" },
    { id: 79, name: 'Samsung Galaxy Star Trios', armazenamento: "4GB", ram: '512MB', processador: "Snapdragon Qualcomm MSM7225A", tela: "TFT LCD" },
    { id: 80, name: 'Samsung Galaxy Core LTE', armazenamento: "8GB", ram: '1GB', processador: "Cortex-A9", tela: "TFT LCD" },
    { id: 81, name: 'Samsung Galaxy S5', armazenamento: "16GB", ram: '2GB', processador: "Krait 400 Qualcomm Snapdragon 801", tela: "Super AMOLED" },
    { id: 82, name: 'Samsung Galaxy S3 mini VE', armazenamento: "8GB", ram: '1GB', processador: "Cortex-A9 Marvell PXA988", tela: "Super AMOLED" },
    { id: 83, name: 'Samsung Galaxy Ace Style', armazenamento: "4GB", ram: '512MB', processador: "Cortex-A9 Broadcom BCM21664T", tela: "TFT LCD" },
    { id: 84, name: 'Samsung Galaxy S3 Neo', armazenamento: "16GB", ram: '1.5GB', processador: "Cortex-A7 Qualcomm Snapdragon 400", tela: "Super AMOLED" },
    { id: 85, name: 'Samsung Galaxy Note 4', armazenamento: "32GB", ram: '3GB', processador: "Cortex A53 / Cortex A57 SAMSUNG Exynos 5433", tela: "Super AMOLED" },
    { id: 86, name: 'Samsung Galaxy Ace 4 LTE', armazenamento: "8GB", ram: '1GB', processador: "Cortex-A53 Qualcomm Snapdragon 410 MSM8916", tela: "Super AMOLED" },
    { id: 87, name: 'Samsung GALAXY S5 mini LTE', armazenamento: "16GB", ram: '1.5GB', processador: "Cortex-A7 SAMSUNG Exynos 3 Quad 3470", tela: "Super AMOLED" },
    { id: 88, name: 'Samsung GALAXY S5 mini', armazenamento: "16GB", ram: '1.5GB', processador: "Cortex-A7 SAMSUNG Exynos 3 Quad 3470", tela: "Super AMOLED" },
    { id: 89, name: 'Samsung Galaxy Star 2', armazenamento: "4GB", ram: '512MB', processador: "Cortex-A7 Spreadtrum SC6815A", tela: "TFT LCD" },
    { id: 90, name: 'Samsung Galaxy S5 Neo', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A53 SAMSUNG Exynos 7580", tela: "Super AMOLED" },
    { id: 91, name: 'Samsung Galaxy Ace NXT', armazenamento: "4GB", ram: '512MB', processador: "Cortex-A7 Spreadtrum Dolphin SC7715", tela: "TFT LCD" },
    { id: 92, name: 'Samsung Galaxy Alpha', armazenamento: "32GB", ram: '2GB', processador: "Cortex A15 / Cortex A7 SAMSUNG Exynos 5 Octa 5430", tela: "Super AMOLED" },
    { id: 93, name: 'Samsung Galaxy Mega 2', armazenamento: "8GB", ram: '1.5GB', processador: "Snapdragon 410 Qualcomm Cortex-A53", tela: "LCD" },
    { id: 94, name: 'Samsung Galaxy Note edge', armazenamento: "64GB", ram: '3GB', processador: "Qualcomm Snapdragon 805 APQ8084", tela: "Super AMOLED" },
    { id: 95, name: 'Samsung Galaxy A5', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A53 Qualcomm Snapdragon 410", tela: "Super AMOLED" },
    { id: 96, name: 'Samsung Galaxy A3', armazenamento: "16GB", ram: '1GB', processador: "Cortex-A53 Qualcomm Snapdragon 410", tela: "Super AMOLED" },
    { id: 97, name: 'Samsung Galaxy Gran Prime Duos TV', armazenamento: "8GB", ram: '1GB', processador: "Cortex-A53 Qualcomm Snapdragon 410 MSM8916", tela: "TFT LCD" },
    { id: 98, name: 'Samsung Galaxy Core Plus', armazenamento: "4GB", ram: '768MB', processador: "Cortex-A9 Broadcom BCM28155", tela: "TFT LCD" },
    { id: 99, name: 'Samsung Z1', armazenamento: "4GB", ram: '768MB', processador: "Cortex-A7 Spreadtrum SC7727S", tela: "PLS LCD" },
    { id: 100, name: 'Samsung Galaxy E5', armazenamento: "16GB", ram: '1.5GB', processador: "Cortex-A53 Qualcomm Snapdragon 410 MSM8916", tela: "Super AMOLED" },
    { id: 101, name: 'Samsung Galaxy E7', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A53 Qualcomm Snapdragon 410 MSM8916", tela: "Super AMOLED" },
    { id: 102, name: 'Samsung Galaxy Core Prime', armazenamento: "8GB", ram: '1GB', processador: "Cortex-A53 Qualcomm Snapdragon 410 MSM8916", tela: "LCD" },
    { id: 103, name: 'Samsung Galaxy J1', armazenamento: "4GB", ram: '768MB', processador: "Cortex-A7 Spreadtrum", tela: "TFT LCD" },
    { id: 104, name: 'Samsung Galaxy Win 2', armazenamento: "8GB", ram: '1GB', processador: "Cortex-A53 Qualcomm Snapdragon 410 MSM8916", tela: "TFT LCD" },
    { id: 105, name: 'Samsung Galaxy J7', armazenamento: "16GB", ram: '1.5GB', processador: "Cortex-A53 SAMSUNG Exynos 7580", tela: "Super AMOLED" },
    { id: 106, name: 'Samsung Galaxy A8', armazenamento: "32GB", ram: '2GB', processador: "Qualcomm Snapdragon 615 MSM8939", tela: "Super AMOLED" },
    { id: 107, name: 'Samsung Galaxy S4 Mini Plus', armazenamento: "8GB", ram: '1.5GB', processador: "Cortex-A53 Qualcomm Snapdragon 410 MSM8916", tela: "Super AMOLED" },
    { id: 108, name: 'Samsung Galaxy S6 edge plus', armazenamento: "32GB", ram: '4GB', processador: "SAMSUNG Exynos 7420", tela: "Super AMOLED" },
    { id: 109, name: 'Samsung Galaxy J2', armazenamento: "8GB", ram: '1GB', processador: "Cortex-A7 SAMSUNG Exynos 3 Quad 3475", tela: "Super AMOLED" },
    { id: 110, name: 'Samsung Z3', armazenamento: "8GB", ram: '1GB', processador: "Cortex-A7 Spreadtrum SC7730", tela: "Super AMOLED" },
    { id: 111, name: 'Samsung Galaxy J1 Ace', armazenamento: "4GB", ram: '512MB', processador: "Cortex-A53 Marvell PXA1908", tela: "Super AMOLED" },
    { id: 112, name: 'Samsung Galaxy On 7', armazenamento: "16GB", ram: '1.5GB', processador: "Cortex-A53 Qualcomm Snapdragon 410 MSM8916", tela: "TFT LCD" },
    { id: 113, name: 'Samsung Galaxy On 5', armazenamento: "8GB", ram: '1.5GB', processador: "Cortex-A7 SAMSUNG Exynos 3475", tela: "TFT LCD" },
    { id: 114, name: 'Samsung Galaxy J3', armazenamento: "8GB", ram: '1.5GB', processador: "Cortex-A7 Spreadtrum", tela: "Super AMOLED" },
    { id: 115, name: 'Samsung Galaxy A5 2016', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A53 SAMSUNG Exynos 7 Octa 7580", tela: "Super AMOLED" },
    { id: 116, name: 'Samsung Galaxy A3 2016', armazenamento: "16GB", ram: '1.5GB', processador: "Cortex-A53 SAMSUNG Exynos 7578", tela: "Super AMOLED" },
    { id: 117, name: 'Samsung Galaxy On 5', armazenamento: "8GB", ram: '1.5GB', processador: "Cortex-A7 SAMSUNG Exynos 3475", tela: "TFT LCD" },
    { id: 118, name: 'Samsung Galaxy A9 2016', armazenamento: "32GB", ram: '4GB', processador: "MSM8976 Qualcomm Snapdragon 652", tela: "Super AMOLED" },
    { id: 119, name: 'Samsung Galaxy Gran Prime', armazenamento: "8GB", ram: '1GB', processador: "Snapdragon 410 Qualcomm MSM8916", tela: "TFT LCD" },
    { id: 120, name: 'Samsung Galaxy Gran Prime LTE', armazenamento: "8GB", ram: '1GB', processador: "Cortex-A53 Qualcomm Snapdragon 410 MSM8916", tela: "TFT LCD" },
    { id: 121, name: 'Samsung Galaxy S7', armazenamento: "32GB", ram: '4GB', processador: "SAMSUNG Exynos 8 Octa 8890", tela: "Super AMOLED" },
    { id: 122, name: 'Samsung Galaxy J1 Mini', armazenamento: "8GB", ram: '768MB', processador: "Cortex-A7 Spreadtrum SC8830", tela: "TFT LCD" },
    { id: 123, name: 'Samsung Galaxy Xcover 3', armazenamento: "8GB", ram: '1.5GB', processador: "Cortex-A53 Marvell PXA1908", tela: "TFT LCD" },
    { id: 124, name: 'Samsung Galaxy C5', armazenamento: "64GB", ram: '4GB', processador: "MSM8952 Qualcomm Snapdragon 617", tela: "Super AMOLED" },
    { id: 125, name: 'Samsung Galaxy C7', armazenamento: "64GB", ram: '4GB', processador: "Cortex-A53 Qualcomm Snapdragon 625 MSM8953", tela: "Super AMOLED" },
    { id: 126, name: 'Samsung Galaxy J2 2016', armazenamento: "8GB", ram: '1.5GB', processador: "Cortex-A7 Spreadtrum SC8830", tela: "Super AMOLED" },
    { id: 127, name: 'Samsung Galaxy J Max', armazenamento: "8GB", ram: '1.5GB', processador: "Cortex-A7", tela: "TFT LCD" },
    { id: 128, name: 'Samsung Galaxy On 7 Pro', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A53 Qualcomm Snapdragon 410 MSM8916", tela: "TFT LCD" },
    { id: 129, name: 'Samsung Galaxy On 5 Pro', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A7 SAMSUNG Exynos 3475", tela: "TFT LCD" },
    { id: 130, name: 'Samsung Galaxy J2 Pro', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A7 Spreadtrum SC8830", tela: "Super AMOLED" },
    { id: 131, name: 'Samsung Galaxy Note 7', armazenamento: "64GB", ram: '4GB', processador: "SAMSUNG Exynos 8 Octa 8890", tela: "Super AMOLED" },
    { id: 132, name: 'Samsung Galaxy J1 Ace 4G', armazenamento: "8GB", ram: '1GB', processador: "Cortex-A53 Marvell PXA1908", tela: "Super AMOLED" },
    { id: 133, name: 'Samsung Z2', armazenamento: "8GB", ram: '1GB', processador: "Cortex-A7 Spreadtrum SC9830A", tela: "IPS LCD" },
    { id: 134, name: 'Samsung Galaxy On 7 2016', armazenamento: "32GB", ram: '3GB', processador: "Cortex-A53 Qualcomm Snapdragon 625 MSM8953", tela: "LCD" },
    { id: 135, name: 'Samsung Galaxy On 8', armazenamento: "16GB", ram: '3GB', processador: "Cortex-A53 SAMSUNG Exynos 7 Octa 7580", tela: "Super AMOLED" },
    { id: 136, name: 'Samsung Galaxy On 5 2016', armazenamento: "32GB", ram: '3GB', processador: "MSM8952 Qualcomm Snapdragon 617", tela: "PLS TFT" },
    { id: 137, name: 'Samsung Galaxy J5 Prime', armazenamento: "32GB", ram: '2GB', processador: "Cortex-A53 SAMSUNG Exynos 7 Quad 7570", tela: "TFT LCD" },
    { id: 138, name: 'Samsung Galaxy A8 2016', armazenamento: "32GB", ram: '3GB', processador: "SAMSUNG Exynos 7 Octa 7420", tela: "Super AMOLED" },
     { id: 139, name: 'Samsung Galaxy C9 Pro', armazenamento: "64GB", ram: '6GB', processador: "MSM8976 Qualcomm Snapdragon 653", tela: "Super AMOLED" },
     { id: 140, name: 'Samsung Galaxy J2 Prime', armazenamento: "16GB", ram: '1.4GB', processador: "Cortex-A53 MediaTek MT6737T", tela: "PLS TFT" },
     { id: 141, name: 'Samsung Galaxy A3 2017', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A53 SAMSUNG Exynos 7870 Octa", tela: "Super AMOLED  " },
     { id: 142, name: 'Samsung Galaxy A5 2017', armazenamento: "64GB", ram: '3GB', processador: "Cortex-A53 SAMSUNG Exynos 7 Octa 7880", tela: "Super AMOLED" },
     { id: 143, name: 'Samsung Galaxy A7 2017', armazenamento: "32GB", ram: '3GB', processador: "Cortex-A53 SAMSUNG Exynos 7 Octa 7880", tela: "Super AMOLED" },
     { id: 144, name: 'Samsung Galaxy C7 Pro', armazenamento: "64GB", ram: '4GB', processador: "Cortex-A53 Qualcomm Snapdragon 625 MSM8953", tela: "Super AMOLED" },
     { id: 145, name: 'Samsung Galaxy C5 Pro', armazenamento: "64GB", ram: '4GB', processador: "MSM8953 Pro Qualcomm Snapdragon 626", tela: "Super AMOLED" },
     { id: 146, name: 'Samsung Z4', armazenamento: "8GB", ram: '1GB', processador: "Cortex-A7 Spreadtrum SC9830A", tela: "LCD" },
     { id: 147, name: 'Samsung Galaxy Note FE', armazenamento: "64GB", ram: '4GB', processador: "SAMSUNG Exynos 8 Octa 8890", tela: "Super AMOLED" },
     { id: 148, name: 'Samsung Galaxy J7 Max', armazenamento: "32GB", ram: '4GB', processador: "Helio P20 MediaTek MT6757", tela: "PLS TFT" },
     { id: 149, name: 'Samsung Galaxy J7 2017', armazenamento: "16GB", ram: '3GB', processador: "Cortex-A53 SAMSUNG Exynos 7870 Octa", tela: "Super AMOLED" },
     { id: 150, name: 'Samsung Galaxy J5 2017', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A53 SAMSUNG Exynos 7870 Octa", tela: "Super AMOLED" },
     { id: 151, name: 'Samsung Galaxy J3 2017', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A53 SAMSUNG Exynos 7570", tela: "PLS TFT" },
     { id: 152, name: 'Samsung Galaxy J7 Pro', armazenamento: "64GB", ram: '3GB', processador: "Cortex-A53 SAMSUNG Exynos 7870 Octa", tela: "Super AMOLED" },
     { id: 153, name: 'Samsung Galaxy A8 Plus 2018', armazenamento: "64GB", ram: '4GB', processador: "SAMSUNG Exynos 7 Octa 7885", tela: "Super AMOLED" },
     { id: 154, name: 'Samsung Galaxy J2 Pro 2018', armazenamento: "16GB", ram: '1.5GB', processador: "Qualcomm Snapdragon 425 MSM8917", tela: "Super AMOLED" },
     { id: 155, name: 'Samsung Galaxy J7 Duo', armazenamento: "32GB", ram: '3GB', processador: "SAMSUNG Exynos 7 Octa 7884", tela: "Super AMOLED" },
     { id: 156, name: 'Samsung Galaxy A6', armazenamento: "32GB", ram: '3GB', processador: "Cortex-A53 SAMSUNG Exynos 7870 Octa", tela: "Super AMOLED" },
     { id: 157, name: 'Samsung Galaxy J4', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A53 SAMSUNG Exynos 7 Quad 7570", tela: "Super AMOLED" },
     { id: 158, name: 'Samsung Galaxy J7 2018', armazenamento: "32GB", ram: '2GB', processador: "Cortex-A53 SAMSUNG Exynos 7870 Octa", tela: "TFT LCD" },
     { id: 159, name: 'Samsung Galaxy J3 2018', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A53 SAMSUNG Exynos 7570", tela: "IPS LCD" },
     { id: 160, name: 'Samsung Galaxy J4 Plus', armazenamento: "32GB", ram: '2GB', processador: "Snapdragon 425 Qualcomm SDM425", tela: "IPS LCD" },
     { id: 161, name: 'Samsung Galaxy A9', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 660 Qualcomm SDM660", tela: "Super AMOLED" },
     { id: 162, name: 'Samsung Galaxy A6s', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 660 Qualcomm SDM660", tela: "PLS LCD" },
     { id: 163, name: 'Samsung W2018', armazenamento: "64GB", ram: '6GB', processador: "Snapdragon 835 Qualcomm SDM835", tela: "Super AMOLED" },
     { id: 164, name: 'Samsung W2019', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 845 Qualcomm SDM845", tela: "Super AMOLED" },
     { id: 165, name: 'Samsung Galaxy A8s', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 710 Qualcomm SDM710", tela: "TFT LCD" },
     { id: 166, name: 'Samsung Galaxy M10', armazenamento: "32GB", ram: '3GB', processador: "Cortex-A53 SAMSUNG Exynos 7870 Octa", tela: "PLS TFT" },
     { id: 167, name: 'Samsung Galaxy M20', armazenamento: "64GB", ram: '4GB', processador: "SAMSUNG Exynos 7 Octa 7904", tela: "PLS TFT" },
     { id: 168, name: 'Samsung Galaxy M30', armazenamento: "64GB", ram: '4GB', processador: "SAMSUNG Exynos 7 Octa 7904", tela: "Super AMOLED" },
     { id: 169, name: 'Samsung Galaxy A9 Pro', armazenamento: "32GB", ram: '4GB', processador: "MSM8976 Qualcomm Snapdragon 652", tela: "Super AMOLED" },
     { id: 170, name: 'Samsung Galaxy Fold', armazenamento: "512GB", ram: '12GB', processador: "Snapdragon 855 Qualcomm SDM855", tela: "Dynamic AMOLED" },
     { id: 171, name: 'Samsung Galaxy S10 5G', armazenamento: "256GB", ram: '8GB', processador: "Snapdragon 855 Qualcomm SDM855", tela: "Dynamic AMOLED" },
     { id: 172, name: 'Samsung Galaxy A50', armazenamento: "64GB", ram: '4GB', processador: "SAMSUNG Exynos 7 Octa 9610", tela: "Super AMOLED" },
     { id: 173, name: 'Samsung Galaxy A20', armazenamento: "32GB", ram: '3GB', processador: "SAMSUNG Exynos 7 Octa 7884", tela: "Super AMOLED" },
     { id: 174, name: 'Samsung Galaxy A70', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 675 Qualcomm SDM675", tela: "Super AMOLED" },
     { id: 175, name: 'Samsung Galaxy A80', armazenamento: "128GB", ram: '8GB', processador: "Snapdragon 730G Qualcomm SDM730G", tela: "Super AMOLED" },
     { id: 176, name: 'Samsung Galaxy Xcover 4s', armazenamento: "32GB", ram: '3GB', processador: "SAMSUNG Exynos 7 Octa 7885", tela: "IPS LCD" },
     { id: 177, name: 'Samsung Galaxy Note 10 Plus', armazenamento: "512GB", ram: '12GB', processador: "SAMSUNG Exynos 9825", tela: "Dynamic AMOLED" },
     { id: 178, name: 'Samsung Galaxy A10e', armazenamento: "32GB", ram: '2GB', processador: "SAMSUNG Exynos 7 Octa 7884B", tela: "TFT LCD" },
     { id: 179, name: 'Samsung Galaxy A50s', armazenamento: "128GB", ram: '4GB', processador: "SAMSUNG Exynos 9611", tela: "Super AMOLED" },
     { id: 180, name: 'Samsung Galaxy Note 10 Plus 5G', armazenamento: "512GB", ram: '12GB', processador: "Snapdragon 855 Qualcomm SDM855", tela: "Dynamic AMOLED" },
     { id: 181, name: 'Samsung Galaxy M10s', armazenamento: "32GB", ram: '3GB', processador: "SAMSUNG Exynos 7 Octa 7884B", tela: "Super AMOLED" },
     { id: 182, name: 'Samsung Galaxy M30s', armazenamento: "64GB", ram: '4GB', processador: "SAMSUNG Exynos 9611", tela: "Super AMOLED" },
     { id: 183, name: 'Samsung Galaxy A70s', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 675 Qualcomm SDM675", tela: "Super AMOLED" },
     { id: 184, name: 'Samsung Galaxy Fold 5G', armazenamento: "512GB", ram: '12GB', processador: "Snapdragon 855 Plus Qualcomm SDM855", tela: "Dynamic AMOLED" },
     { id: 185, name: 'Samsung Galaxy S20 5G', armazenamento: "128GB", ram: '12GB', processador: "SAMSUNG Exynos 990", tela: "Dynamic AMOLED" },
     { id: 186, name: 'Samsung Galaxy M21', armazenamento: "64GB", ram: '4GB', processador: "SAMSUNG Exynos 9611", tela: "Super AMOLED" },
     { id: 187, name: 'Samsung Galaxy M11', armazenamento: "32GB", ram: '3GB', processador: "Snapdragon 450 Qualcomm SDM450", tela: "PLS TFT" },
     { id: 188, name: 'Samsung Galaxy A71 5G', armazenamento: "128GB", ram: '6GB', processador: "SAMSUNG Exynos 980", tela: "Super AMOLED" },
     { id: 189, name: 'Samsung Galaxy A21', armazenamento: "32GB", ram: '3GB', processador: "Helio P35 MediaTek MT6765", tela: "TFT LCD" },
     { id: 190, name: 'Samsung Galaxy A51 5G', armazenamento: "128GB", ram: '6GB', processador: "SAMSUNG Exynos 980", tela: "Super AMOLED" },
     { id: 191, name: 'Samsung Galaxy A Quantum', armazenamento: "128GB", ram: '8GB', processador: "SAMSUNG Exynos 980", tela: "Super AMOLED" },
     { id: 192, name: 'Samsung Galaxy Z Flip 5G', armazenamento: "256GB", ram: '8GB', processador: "Snapdragon 865 Plus Qualcomm SM8250", tela: "Dynamic AMOLED" },
     { id: 193, name: 'Samsung Galaxy M01', armazenamento: "32GB", ram: '3GB', processador: "Snapdragon 439 Qualcomm SDM439", tela: "PLS TFT" },
     { id: 194, name: 'Samsung Galaxy M01s', armazenamento: "32GB", ram: '3GB', processador: "Helio P22 MediaTek MT6762", tela: "PLS TFT LCD" },
     { id: 195, name: 'Samsung Galaxy M01 Core', armazenamento: "16GB", ram: '1GB', processador: "MediaTek MT6739", tela: "PLS TFT LCD" },
     { id: 196, name: 'Samsung Galaxy M31s', armazenamento: "128GB", ram: '6GB', processador: "SAMSUNG Exynos 9611", tela: "Super AMOLED" },
     { id: 197, name: 'Samsung Galaxy M31 Prime', armazenamento: "128GB", ram: '6GB', processador: "SAMSUNG Exynos 9611", tela: "Super AMOLED" },
     { id: 198, name: 'Samsung W21', armazenamento: "512GB", ram: '12GB', processador: "Snapdragon 865 Plus Qualcomm SM8250", tela: "Dynamic AMOLED 2X" },
     { id: 199, name: 'Samsung Galaxy M02s', armazenamento: "32GB", ram: '3GB', processador: "Snapdragon 450 Qualcomm SDM450", tela: "PLS LCD" },
     { id: 200, name: 'Samsung Galaxy XCover 5', armazenamento: "64GB", ram: '4GB', processador: "SAMSUNG Exynos 850", tela: "PLS TFT LCD" },
     { id: 201, name: 'Samsung Galaxy Quantum 2', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 855 Plus Qualcomm SDM855", tela: "Dynamic AMOLED 2X" },
     { id: 202, name: 'Samsung Galaxy F12', armazenamento: "64GB", ram: '4GB', processador: "SAMSUNG Exynos 850", tela: "IPS LCD" },
     { id: 203, name: 'Samsung Galaxy F02s', armazenamento: "32GB", ram: '3GB', processador: "Snapdragon 450 Qualcomm SDM450", tela: "IPS LCD" },
     { id: 204, name: 'Samsung Galaxy F52 5G', armazenamento: "128GB", ram: '8GB', processador: "Snapdragon 750G Qualcomm SM7225", tela: "TFT LCD" },
     { id: 205, name: 'Samsung Galaxy F22', armazenamento: "128GB", ram: '4GB', processador: "Helio G80 MediaTek", tela: "Super AMOLED" },
     { id: 206, name: 'Samsung Galaxy M21 2021', armazenamento: "64GB", ram: '4GB', processador: "SAMSUNG Exynos 9611", tela: "Super AMOLED" },
     { id: 207, name: 'Samsung Galaxy A12 Nacho', armazenamento: "32GB", ram: '3GB', processador: "SAMSUNG Exynos 850", tela: "PLS TFT LCD" },
     { id: 208, name: 'Samsung Galaxy M32 5G', armazenamento: "128GB", ram: '6GB', processador: "Dimensity 720 MediaTek MT6853", tela: "TFT LCD" },
     { id: 209, name: 'Samsung Galaxy A13 5G', armazenamento: "64GB", ram: '4GB', processador: "Dimensity 700 MediaTek MT6833", tela: "IPS LCD" },
     { id: 210, name: 'Samsung Galaxy M33', armazenamento: "128GB", ram: '6GB', processador: "SAMSUNG Exynos 1280", tela: "TFT LCD" },
     { id: 211, name: 'Samsung Galaxy M23', armazenamento: "128GB", ram: '4GB', processador: "Snapdragon 750G Qualcomm SM7225", tela: "TFT LCD" },
     { id: 212, name: 'Samsung Galaxy F23', armazenamento: "128GB", ram: '4GB', processador: "Snapdragon 750G Qualcomm SM7225", tela: "IPS LCD" },
     { id: 213, name: 'Samsung Galaxy Quantum 3', armazenamento: "128GB", ram: '8GB', processador: "Dimensity 900 MediaTek MT6877", tela: "Super AMOLED Plus" },
     { id: 214, name: 'Samsung Galaxy A7', armazenamento: "16GB", ram: '2GB', processador: "Qualcomm Snapdragon 615 MSM8939", tela: "Super AMOLED" },
     { id: 215, name: 'Samsung Galaxy S6 edge', armazenamento: "64GB", ram: '3GB', processador: "SAMSUNG Exynos 7420", tela: "Super AMOLED" },
     { id: 216, name: 'Samsung Galaxy S6', armazenamento: "32GB", ram: '3GB', processador: "SAMSUNG Exynos 7420", tela: "Super AMOLED" },
     { id: 217, name: 'Samsung Galaxy J1 2016', armazenamento: "8GB", ram: '1GB', processador: "Cortex-A7 SAMSUNG Exynos 3 Quad 3475", tela: "Super AMOLED" },
     { id: 218, name: 'Samsung Galaxy J7 Metal (2016)', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A53 SAMSUNG Exynos 7 Octa 7870", tela: "Super AMOLED" },
     { id: 219, name: 'Samsung Galaxy J5 Metal (2016)', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A53 Qualcomm Snapdragon 410 MSM8916", tela: "Super AMOLED" },
     { id: 220, name: 'Samsung Galaxy A7 2016', armazenamento: "16GB", ram: '3GB', processador: "Cortex-A53 SAMSUNG Exynos 7 Octa 7580", tela: "Super AMOLED" },
     { id: 221, name: 'Samsung Galaxy J5', armazenamento: "16GB", ram: '1.5GB', processador: "Cortex-A53 Qualcomm Snapdragon 410 MSM8916  ", tela: "Super AMOLED" },
     { id: 222, name: 'Samsung Galaxy J6 Plus', armazenamento: "32GB", ram: '3GB', processador: "Snapdragon 425 Qualcomm SDM425", tela: "IPS LCD" },
     { id: 223, name: 'Samsung Galaxy J2 Core', armazenamento: "16GB", ram: '1GB', processador: "SAMSUNG Exynos 7 Quad 7570", tela: "PLS TFT LCD" },
     { id: 224, name: 'Samsung Galaxy J4 Core', armazenamento: "16GB", ram: '1GB', processador: "Snapdragon 425 Qualcomm SDM425", tela: "TFT LCD" },
     { id: 225, name: 'Samsung Galaxy J7 Neo', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A53 SAMSUNG Exynos 7870 Octa", tela: "Super AMOLED" },
     { id: 226, name: 'Samsung Galaxy J8', armazenamento: "64GB", ram: '4GB', processador: "Snapdragon 450 Qualcomm SDM450", tela: "Super AMOLED" },
     { id: 227, name: 'Samsung Galaxy A8 2018', armazenamento: "64GB", ram: '4GB', processador: "SAMSUNG Exynos 7 Octa 7885", tela: "Super AMOLED" },
     { id: 228, name: 'Samsung Galaxy S9 Plus', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 845 Qualcomm SDM845", tela: "Super AMOLED" },
     { id: 229, name: 'Samsung Galaxy S8', armazenamento: "64GB", ram: '4GB', processador: "8895 SAMSUNG Exynos 9", tela: "Super AMOLED" },
     { id: 230, name: 'Samsung Galaxy S9', armazenamento: "128GB", ram: '4GB', processador: "Snapdragon 845 Qualcomm SDM845", tela: "Super AMOLED" },
     { id: 231, name: 'Samsung Galaxy S8 Plus', armazenamento: "64GB", ram: '4GB', processador: "8895 SAMSUNG Exynos 9", tela: "Super AMOLED" },
     { id: 232, name: 'Samsung Galaxy Note 8', armazenamento: "64GB", ram: '6GB', processador: "8895 SAMSUNG Exynos 9", tela: "Super AMOLED" },
     { id: 233, name: 'Samsung Galaxy J6', armazenamento: "32GB", ram: '2GB', processador: "Cortex-A53 SAMSUNG Exynos 7870 Octa", tela: "Super AMOLED" },
     { id: 234, name: 'Samsung Galaxy J5 Pro', armazenamento: "32GB", ram: '2GB', processador: "Cortex-A53 SAMSUNG Exynos 7870 Octa", tela: "Super AMOLED" },
     { id: 235, name: 'Samsung Galaxy Z Flip', armazenamento: "256GB", ram: '8GB', processador: "Snapdragon 855 Plus Qualcomm SDM855", tela: "Dynamic AMOLED" },
     { id: 236, name: 'Samsung Galaxy A6 Plus', armazenamento: "64GB", ram: '4GB', processador: "Cortex-A53 Qualcomm Snapdragon 450", tela: "Super AMOLED" },
     { id: 237, name: 'Samsung Galaxy Note 9', armazenamento: "128GB", ram: '6GB', processador: "Qualcomm Snapdragon 845", tela: "Super AMOLED" },
     { id: 238, name: 'Samsung Galaxy S22 Plus 5G', armazenamento: "256GB", ram: '8GB', processador: "Snapdragon 8 Gen1 Qualcomm SM8450", tela: "Dynamic AMOLED 2X" },
     { id: 239, name: 'Samsung Galaxy J7 Prime 2', armazenamento: "32GB", ram: '3GB', processador: "Cortex-A53 SAMSUNG Exynos 7870 Octa", tela: "PLS TFT" },
     { id: 240, name: 'Samsung Galaxy S22 Ultra 5G', armazenamento: "512GB", ram: '12GB', processador: "Snapdragon 8 Gen1 Qualcomm SM8450", tela: "Dynamic AMOLED 2X" },
     { id: 241, name: 'Samsung Galaxy S20 Plus 5G', armazenamento: "128GB", ram: '12GB', processador: "SAMSUNG Exynos 990", tela: "Dynamic AMOLED" },
     { id: 242, name: 'Samsung Galaxy S22 5G', armazenamento: "256GB", ram: '8GB', processador: "Snapdragon 8 Gen1 Qualcomm SM8450", tela: "Dynamic AMOLED 2X" },
     { id: 243, name: 'Samsung Galaxy Note 10', armazenamento: "256GB", ram: '8GB', processador: "SAMSUNG Exynos 9825", tela: "Dynamic AMOLED" },
     { id: 244, name: 'Samsung Galaxy S20 Ultra 5G', armazenamento: "128GB", ram: '12GB', processador: "SAMSUNG Exynos 990", tela: "Dynamic AMOLED" },
     { id: 245, name: 'Samsung Galaxy S10e', armazenamento: "128GB", ram: '6GB', processador: "SAMSUNG Exynos 9 Octa 9820", tela: "Dynamic AMOLED" },
     { id: 246, name: 'Samsung Galaxy M51', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 730 Qualcomm SM7150-AA", tela: "Super AMOLED Plus" },
     { id: 247, name: 'Samsung Galaxy Z Fold 2', armazenamento: "256GB", ram: '12GB', processador: "Snapdragon 865 Plus Qualcomm SM8250", tela: "Dynamic AMOLED 2X" },
     { id: 248, name: 'Samsung Galaxy S10', armazenamento: "128GB", ram: '8GB', processador: "SAMSUNG Exynos 9 Octa 9820", tela: "Dynamic AMOLED" },
     { id: 249, name: 'Samsung Galaxy S10 Plus', armazenamento: "128GB", ram: '8GB', processador: "SAMSUNG Exynos 9 Octa 9820", tela: "Dynamic AMOLED" },
     { id: 250, name: 'Samsung Galaxy J7 Prime', armazenamento: "32GB", ram: '3GB', processador: "Cortex-A53 SAMSUNG Exynos 7870 Octa", tela: "PLS TFT" },
     { id: 251, name: 'Samsung Galaxy S20', armazenamento: "128GB", ram: '8GB', processador: "SAMSUNG Exynos 990", tela: "Dynamic AMOLED" },
     { id: 252, name: 'Samsung Galaxy M53 5G', armazenamento: "128GB", ram: '8GB', processador: "Dimensity 900 MediaTek MT6877", tela: "Super AMOLED Plus" },
     { id: 253, name: 'Samsung Galaxy Z Fold 3 5G', armazenamento: "512GB", ram: '12GB', processador: "Snapdragon 888 Qualcomm SM8350", tela: "Dynamic AMOLED 2X" },
     { id: 254, name: 'Samsung Galaxy A32 5G', armazenamento: "128GB", ram: '4GB', processador: "Dimensity 720 MediaTek MT6853", tela: "IPS LCD" },
     { id: 255, name: 'Samsung Galaxy S20 Ultra', armazenamento: "128GB", ram: '12GB', processador: "SAMSUNG Exynos 990", tela: "Dynamic AMOLED" },
     { id: 256, name: 'Samsung Galaxy Note 10 Lite', armazenamento: "128GB", ram: '6GB', processador: "SAMSUNG Exynos 9 Octa 9810", tela: "Super AMOLED" },
     { id: 257, name: 'Samsung Galaxy A30s', armazenamento: "64GB", ram: '4GB', processador: "SAMSUNG Exynos 7 Octa 7904", tela: "Super AMOLED" },
     { id: 258, name: 'Samsung Galaxy A7 2018', armazenamento: "64GB", ram: '4GB', processador: "SAMSUNG Exynos 7 Octa 7885", tela: "Super AMOLED" },
     { id: 259, name: 'Samsung Galaxy A72', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 720G Qualcomm SM7125", tela: "Super AMOLED" },
     { id: 260, name: 'Samsung Galaxy A52', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 720G Qualcomm SM7125", tela: "Super AMOLED" },
     { id: 261, name: 'Samsung Galaxy A52 5G', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 750G Qualcomm SM7225", tela: "Super AMOLED" },
     { id: 262, name: 'Samsung Galaxy F12', armazenamento: "64GB", ram: '4GB', processador: "SAMSUNG Exynos 850", tela: "IPS LCD" },
     { id: 263, name: 'Samsung Galaxy F02s', armazenamento: "32GB", ram: '3GB', processador: "Snapdragon 450 Qualcomm SDM450", tela: "IPS LCD" },
     { id: 264, name: 'Samsung Galaxy Quantum 2', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 855 Plus Qualcomm SDM855", tela: "Dynamic AMOLED 2X" },
     { id: 265, name: 'Samsung Galaxy S20 FE Snapdragon', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 865 Qualcomm SM8250", tela: "Super AMOLED" },
     { id: 266, name: 'Samsung Galaxy F52 5G', armazenamento: "128GB", ram: '8GB', processador: "Snapdragon 750G Qualcomm SM7225", tela: "TFT LCD" },
     { id: 267, name: 'Samsung Galaxy M12', armazenamento: "64GB", ram: '4GB', processador: "SAMSUNG Exynos 850", tela: "PLS TFT LCD" },
     { id: 268, name: 'Samsung Galaxy A22 5G', armazenamento: "128GB", ram: '4GB', processador: "Dimensity 700 MediaTek MT6833", tela: "TFT LCD" },
     { id: 269, name: 'Samsung Galaxy A22', armazenamento: "128GB", ram: '4GB', processador: "Helio G80 MediaTek", tela: "Super AMOLED" },
     { id: 270, name: 'Samsung Galaxy F22', armazenamento: "128GB", ram: '4GB', processador: "Helio G80 MediaTek", tela: "Super AMOLED" },
     { id: 271, name: 'Samsung Galaxy M21 2021', armazenamento: "64GB", ram: '4GB', processador: "SAMSUNG Exynos 9611", tela: "Super AMOLED" },
     { id: 272, name: 'Samsung Galaxy M32', armazenamento: "128GB", ram: '6GB', processador: "Helio G80 MediaTek", tela: "Super AMOLED" },
     { id: 273, name: 'Samsung Galaxy M62', armazenamento: "128GB", ram: '8GB', processador: "SAMSUNG Exynos 9825", tela: "Super AMOLED Plus" },
     { id: 274, name: 'Samsung Galaxy A12 Nacho', armazenamento: "32GB", ram: '3GB', processador: "SAMSUNG Exynos 850", tela: "PLS TFT LCD" },
     { id: 275, name: 'Samsung Galaxy Z Flip 3 5G', armazenamento: "256GB", ram: '8GB', processador: "Snapdragon 888 Qualcomm SM8350", tela: "Dynamic AMOLED 2X" },
     { id: 276, name: 'Samsung Galaxy Z Fold 3 5G', armazenamento: "512GB", ram: '12GB', processador: "Snapdragon 888 Qualcomm SM8350", tela: "Dynamic AMOLED 2X" },
     { id: 277, name: 'Samsung Galaxy A52s 5G', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 778G Qualcomm SM7325", tela: "Super AMOLED" },
     { id: 278, name: 'Samsung Galaxy A03s', armazenamento: "64GB", ram: '4GB', processador: "Helio P35 MediaTek MT6765", tela: "PLS TFT LCD" },
     { id: 279, name: 'Samsung Galaxy M32 5G', armazenamento: "128GB", ram: '6GB', processador: "Dimensity 720 MediaTek MT6853", tela: "TFT LCD" },
     { id: 280, name: 'Samsung Galaxy A21 Simple', armazenamento: "64GB", ram: '3GB', processador: "SAMSUNG Exynos 7 Octa 7884B", tela: "TFT LCD" },
     { id: 281, name: 'Samsung Galaxy M22', armazenamento: "128GB", ram: '4GB', processador: "Helio G80 MediaTek", tela: "Super AMOLED Plus" },
     { id: 282, name: 'Samsung Galaxy M52 5G', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 778G Qualcomm SM7325", tela: "Super AMOLED" },
     { id: 283, name: 'Samsung Galaxy A03 Core', armazenamento: "32GB", ram: '2GB', processador: "Unisoc SC9863A", tela: "PLS TFT LCD" },
     { id: 284, name: 'Samsung Galaxy A13 5G', armazenamento: "64GB", ram: '4GB', processador: "Dimensity 700 MediaTek MT6833", tela: "IPS LCD" },
     { id: 285, name: 'Samsung Galaxy S21 FE 5G', armazenamento: "128GB", ram: '6GB', processador: "SAMSUNG Exynos 2100", tela: "Dynamic AMOLED 2X" },
     { id: 286, name: 'Samsung Galaxy A03', armazenamento: "64GB", ram: '4GB', processador: "T606 Unisoc", tela: "TFT LCD" },
     { id: 287, name: 'Samsung Galaxy S22 5G', armazenamento: "256GB", ram: '8GB', processador: "Snapdragon 8 Gen1 Qualcomm SM8450", tela: "Dynamic AMOLED 2X" },
     { id: 288, name: 'Samsung Galaxy S22 Plus 5G', armazenamento: "256GB", ram: '8GB', processador: "Snapdragon 8 Gen1 Qualcomm SM8450", tela: "Dynamic AMOLED 2X" },
     { id: 289, name: 'Samsung Galaxy S22 Ultra 5G', armazenamento: "512GB", ram: '12GB', processador: "Snapdragon 8 Gen1 Qualcomm SM8450", tela: "Dynamic AMOLED 2X" },
     { id: 290, name: 'Samsung Galaxy M33', armazenamento: "128GB", ram: '6GB', processador: "SAMSUNG Exynos 1280", tela: "TFT LCD" },
     { id: 291, name: 'Samsung Galaxy M23', armazenamento: "128GB", ram: '4GB', processador: "Snapdragon 750G Qualcomm SM7225", tela: "TFT LCD" },
     { id: 292, name: 'Samsung Galaxy A13', armazenamento: "32GB", ram: '3GB', processador: "SAMSUNG Exynos 850", tela: "TFT LCD" },
     { id: 293, name: 'Samsung Galaxy A23', armazenamento: "64GB", ram: '4GB', processador: "Snapdragon 680 4G Qualcomm SM6225", tela: "TFT LCD" },
     { id: 294, name: 'Samsung Galaxy F23', armazenamento: "128GB", ram: '4GB', processador: "Snapdragon 750G Qualcomm SM7225", tela: "IPS LCD" },
     { id: 295, name: 'Samsung Galaxy A73 5G', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 778G Qualcomm SM7325", tela: "Super AMOLED Plus" },
     { id: 296, name: 'Samsung Galaxy A33 5G', armazenamento: "128GB", ram: '6GB', processador: "SAMSUNG Exynos 1280", tela: "Super AMOLED" },
     { id: 297, name: 'Samsung Galaxy A53 5G', armazenamento: "256GB", ram: '6GB', processador: "SAMSUNG Exynos 1280", tela: "Super AMOLED" },
     { id: 298, name: 'Samsung Galaxy Quantum 3', armazenamento: "128GB", ram: '8GB', processador: "Dimensity 900 MediaTek MT6877", tela: "Super AMOLED Plus" },
     { id: 299, name: 'Samsung Galaxy M53 5G', armazenamento: "128GB", ram: '8GB', processador: "Dimensity 900 MediaTek MT6877", tela: "Super AMOLED Plus" },
     { id: 300, name: 'Xiaomi Redmi Note', armazenamento: "8GB", ram: '2GB', processador: "Cortex-A7 MediaTek MT6592", tela: "IPS LCD" },
     { id: 301, name: 'Xiaomi Hongmi Redmi 1S', armazenamento: "8GB", ram: '1GB', processador: "Snapdragon 400 Qualcomm MSM8228", tela: "IPS LCD" },
     { id: 302, name: 'Xiaomi Mi 4', armazenamento: "16GB", ram: '2GB', processador: "Snapdragon 801 Qualcomm MSM8974-AC", tela: "IPS LCD" },
     { id: 303, name: 'Xiaomi Redmi Note 4G', armazenamento: "8GB", ram: '2GB', processador: "Snapdragon 400 Qualcomm MSM8928", tela: "IPS LCD" },
     { id: 304, name: 'Xiaomi Mi 3', armazenamento: "64GB", ram: '2GB', processador: "Snapdragon 800 Qualcomm MSM8274AB", tela: "IPS LCD" },
     { id: 305, name: 'Xiaomi Redmi 2', armazenamento: "8GB", ram: '1GB', processador: "Snapdragon 410 Qualcomm MSM8916", tela: "IPS LCD" },
     { id: 306, name: 'Xiaomi Mi Note', armazenamento: "64GB", ram: '3GB', processador: "MSM8974AC Qualcomm Snapdragon 801", tela: "IPS LCD" },
     { id: 307, name: 'Xiaomi Mi Note Pro', armazenamento: "64GB", ram: '4GB', processador: "MSM8994 Qualcomm Snapdragon 810", tela: "IPS LCD" },
     { id: 308, name: 'Xiaomi Mi 5', armazenamento: "64GB", ram: '3GB', processador: "MSM8996 Qualcomm Snapdragon 820", tela: "IPS LCD" },
     { id: 309, name: 'Xiaomi Mi 4i', armazenamento: "16GB", ram: '2GB', processador: "Qualcomm Snapdragon 615 MSM8939", tela: "IPS LCD" },
     { id: 310, name: 'Xiaomi Redmi 2 Pro', armazenamento: "16GB", ram: '2GB', processador: "Snapdragon 410 Qualcomm MSM8916", tela: "IPS LCD" },
     { id: 311, name: 'Xiaomi Redmi Note 2', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A53 MediaTek Helio X10 MT6795", tela: "IPS LCD" },
     { id: 312, name: 'Xiaomi Mi 4c 32GB', armazenamento: "32GB", ram: '3GB', processador: "Qualcomm Snapdragon 808 MSM8992", tela: "IPS LCD" },
     { id: 313, name: 'Xiaomi Mi 4c', armazenamento: "16GB", ram: '2GB', processador: "Qualcomm Snapdragon 808 MSM8992", tela: "IPS LCD" },
     { id: 314, name: 'Xiaomi Redmi Note 3 32GB', armazenamento: "32GB", ram: '3GB', processador: "Cortex-A53 MediaTek Helio X10 MT6795", tela: "IPS LCD" },
     { id: 315, name: 'Xiaomi Redmi Note 3', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A53 MediaTek Helio X10 MT6795", tela: "IPS LCD" },
     { id: 316, name: 'Xiaomi Redmi Note Prime', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A53 Qualcomm Snapdragon 410 MSM8916", tela: "IPS LCD" },
     { id: 317, name: 'Xiaomi Redmi 3', armazenamento: "16GB", ram: '2GB', processador: "MSM8939v2 Qualcomm Snapdragon 616", tela: "IPS LCD" },
     { id: 318, name: 'Xiaomi Redmi Note 3 Pro', armazenamento: "16GB", ram: '2GB', processador: "MSM8956 Qualcomm Snapdragon 650", tela: "IPS LCD" },
     { id: 319, name: 'Xiaomi Mi 4s', armazenamento: "64GB", ram: '3GB', processador: "MSM8992 Qualcomm Snapdragon 808", tela: "IPS LCD" },
     { id: 320, name: 'Xiaomi Mi 5 Standard Edition', armazenamento: "32GB", ram: '3GB', processador: "MSM8996 Qualcomm Snapdragon 820", tela: "IPS LCD" },
     { id: 321, name: 'Xiaomi Mi 5 Exclusive Edition', armazenamento: "128GB", ram: '4GB', processador: "MSM8996 Qualcomm Snapdragon 820", tela: "IPS LCD" },
     { id: 322, name: 'Xiaomi Redmi 3 Pro', armazenamento: "32GB", ram: '3GB', processador: "MSM8939v2 Qualcomm Snapdragon 616", tela: "IPS LCD" },
     { id: 323, name: 'Xiaomi Redmi Note 3 Pro 32GB', armazenamento: "32GB", ram: '3GB', processador: "MSM8956 Qualcomm Snapdragon 650", tela: "IPS LCD" },
     { id: 324, name: 'XXiaomi Mi Max 128GB', armazenamento: "128GB", ram: '4GB', processador: "MSM8976 Qualcomm Snapdragon 652", tela: "IPS LCD" },
     { id: 325, name: 'Xiaomi Mi Max', armazenamento: "64GB", ram: '3GB', processador: "MSM8976 Qualcomm Snapdragon 652", tela: "IPS LCD" },
     { id: 326, name: 'Xiaomi Mi Max 32GB', armazenamento: "32GB", ram: '3GB', processador: "MSM8956 Qualcomm Snapdragon 650", tela: "IPS LCD" },
     { id: 327, name: 'Xiaomi Redmi Pro', armazenamento: "64GB", ram: '3GB', processador: "MT6797 MediaTek Helio X20", tela: "OLED" },
     { id: 328, name: 'Xiaomi Redmi Note 4', armazenamento: "32GB", ram: '3GB', processador: "Snapdragon 625 Qualcomm MSM8953", tela: "IPS LCD" },
     { id: 329, name: 'Xiaomi Redmi Note 4 64GB', armazenamento: "64GB", ram: '4GB', processador: "Snapdragon 625 Qualcomm MSM8953", tela: "IPS LCD" },
     { id: 330, name: 'Xiaomi Mi 5s', armazenamento: "64GB", ram: '3GB', processador: "MSM8996 Qualcomm Snapdragon 821", tela: "IPS LCD" },
     { id: 331, name: 'Xiaomi Mi 5s Plus', armazenamento: "64GB", ram: '4GB', processador: "MSM8996 Qualcomm Snapdragon 821", tela: "IPS LCD" },
     { id: 332, name: 'Xiaomi Mi Note 2', armazenamento: "64GB", ram: '4GB', processador: "MSM8996 Qualcomm Snapdragon 821", tela: "OLED" },
     { id: 333, name: 'Xiaomi Mi Mix', armazenamento: "128GB", ram: '4GB', processador: "MSM8996 Qualcomm Snapdragon 821", tela: "IPS LCD" },
     { id: 334, name: 'Xiaomi Redmi 4', armazenamento: "16GB", ram: '2GB', processador: "Snapdragon 430 Qualcomm MSM8937", tela: "IPS LCD" },
     { id: 335, name: 'Xiaomi Redmi 4 Pro', armazenamento: "32GB", ram: '3GB', processador: "Cortex-A53 Qualcomm Snapdragon 625 MSM8953", tela: "IPS LCD" },
     { id: 336, name: 'Xiaomi Redmi 4a', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A53 Qualcomm Snapdragon 425 MSM8917", tela: "IPS LCD" },
     { id: 337, name: 'Xiaomi Redmi Note 4X', armazenamento: "64GB", ram: '4GB', processador: "Cortex-A53 Qualcomm Snapdragon 625 MSM8953", tela: "IPS LCD" },
     { id: 338, name: 'Xiaomi Redmi 3s', armazenamento: "32GB", ram: '3GB', processador: "Qualcomm Snapdragon 430 MSM8937", tela: "IPS LCD" },
     { id: 339, name: 'Xiaomi Mi 5c', armazenamento: "64GB", ram: '3GB', processador: "Xiaomi Surge S1", tela: "IPS LCD" },
     { id: 340, name: 'Xiaomi Mi Max 2', armazenamento: "64GB", ram: '4GB', processador: "Cortex-A53 Qualcomm Snapdragon 625 MSM8953", tela: "IPS LCD" },
     { id: 341, name: 'Xiaomi Redmi 4X', armazenamento: "32GB", ram: '3GB', processador: "Snapdragon 435 Qualcomm SDM435", tela: "IPS LCD" },
     { id: 342, name: 'Xiaomi Mi 6', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 835 Qualcomm MSM8998", tela: "IPS LCD" },
     { id: 343, name: 'Xiaomi Mi 5X', armazenamento: "64GB", ram: '4GB', processador: "Cortex-A53 Qualcomm Snapdragon 625 MSM8953", tela: "IPS LCD" },
     { id: 344, name: 'Xiaomi Redmi Note 5A', armazenamento: "16GB", ram: '2GB', processador: "Snapdragon 425 Qualcomm SDM425", tela: "IPS LCD" },
     { id: 345, name: 'Xiaomi Redmi Note 5A Prime', armazenamento: "32GB", ram: '3GB', processador: "Snapdragon 435 Qualcomm SDM435", tela: "IPS LCD" },
     { id: 346, name: 'Xiaomi Redmi Note 5A 64GB', armazenamento: "64GB", ram: '4GB', processador: "Snapdragon 435 Qualcomm SDM435", tela: "IPS LCD" },
     { id: 347, name: 'Xiaomi Mi A1', armazenamento: "64GB", ram: '4GB', processador: "Cortex-A53 Qualcomm Snapdragon 625 MSM8953", tela: "IPS LCD" },
     { id: 348, name: 'Xiaomi Mi Mix 2', armazenamento: "256GB", ram: '6GB', processador: "Snapdragon 835 Qualcomm MSM8998", tela: "IPS LCD" },
     { id: 349, name: 'Xiaomi Mi Note 3', armazenamento: "128GB", ram: '6GB', processador: "MSM8956 Qualcomm Snapdragon 660", tela: "IPS LCD" },
     { id: 350, name: 'Xiaomi Redmi Y1', armazenamento: "64GB", ram: '4GB', processador: "Snapdragon 435 Qualcomm SDM435", tela: "IPS LCD" },
     { id: 351, name: 'Xiaomi Redmi 5A', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A53 Qualcomm Snapdragon 425 MSM8917", tela: "IPS LCD" },
     { id: 352, name: 'Xiaomi Redmi 5', armazenamento: "16GB", ram: '2GB', processador: "Cortex-A53 Qualcomm Snapdragon 450", tela: "IPS LCD" },
     { id: 353, name: 'Xiaomi Redmi 5 Plus', armazenamento: "32GB", ram: '3GB', processador: "Cortex-A53 Qualcomm Snapdragon 625 MSM8953", tela: "IPS LCD" },
     { id: 354, name: 'Xiaomi Redmi Note 5 Pro', armazenamento: "64GB", ram: '6GB', processador: "Snapdragon 636 Qualcomm SDM636", tela: "IPS LCD" },
     { id: 355, name: 'Xiaomi Mi Mix 2S', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 845 Qualcomm SDM845", tela: "IPS LCD" },
     { id: 356, name: 'Xiaomi Mi 6X', armazenamento: "64GB", ram: '4GB', processador: "Qualcomm Snapdragon 660", tela: "LTPS IPS LCD" },
     { id: 357, name: 'Xiaomi Redmi Note 5 Al Dual Camera', armazenamento: "32GB", ram: '3GB', processador: "Qualcomm Snapdragon 636", tela: "IPS LCD" },
     { id: 358, name: 'Xiaomi Mi 8', armazenamento: "64GB", ram: '6GB', processador: "Snapdragon 845 Qualcomm SDM845", tela: "AMOLED" },
     { id: 359, name: 'Xiaomi Mi 8 SE', armazenamento: "64GB", ram: '4GB', processador: "Snapdragon 710 Qualcomm SDM710", tela: "AMOLED" },
     { id: 360, name: 'Xiaomi Mi 8 Explorer', armazenamento: "128GB", ram: '8GB', processador: "Snapdragon 845 Qualcomm SDM845", tela: "AMOLED" },
     { id: 361, name: 'Xiaomi Mi Max 3', armazenamento: "64GB", ram: '4GB', processador: "Cortex-A53 Qualcomm Snapdragon 636", tela: "IPS LCD" },
     { id: 362, name: 'Xiaomi Redmi 6 Pro', armazenamento: "32GB", ram: '3GB', processador: "Snapdragon 625 Qualcomm SDM625", tela: "IPS LCD" },
     { id: 363, name: 'Xiaomi Redmi Note 6 Pro', armazenamento: "32GB", ram: '3GB', processador: "Snapdragon 636 Qualcomm SDM636", tela: "IPS LCD" },
     { id: 364, name: 'Xiaomi Mi 8 Pro', armazenamento: "128GB", ram: '8GB', processador: "Snapdragon 845 Qualcomm SDM845", tela: "Super AMOLED" },
     { id: 365, name: 'Xiaomi Black Shark Helo', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 845 Qualcomm SDM845", tela: "AMOLED" },
     { id: 366, name: 'Xiaomi Mi 9 Transparent', armazenamento: "256GB", ram: '12GB', processador: "Snapdragon 855 Qualcomm SDM855", tela: "AMOLED" },
     { id: 367, name: 'Xiaomi Mi Mix 3 5G', armazenamento: "64GB", ram: '6GB', processador: "Snapdragon 855 Qualcomm SDM855", tela: "Super AMOLED" },
     { id: 368, name: 'Xiaomi Mi CC9', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 710 Qualcomm SDM710", tela: "AMOLED" },
     { id: 369, name: 'Xiaomi Mi CC9e', armazenamento: "64GB", ram: '4GB', processador: "Snapdragon 665 Qualcomm SDM665", tela: "AMOLED" },
     { id: 370, name: 'Xiaomi Mi CC9 Meitu Edition', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 710 Qualcomm SDM710", tela: "AMOLED" },
     { id: 371, name: 'Xiaomi Qin AI Life', armazenamento: "32GB", ram: '1GB', processador: "Cortex-A53 Spreadtrum SC9832E", tela: "IPS LCD" },
     { id: 372, name: 'Xiaomi Black Shark 2 Pro', armazenamento: "128GB", ram: '8GB', processador: "Snapdragon 855 Plus Qualcomm SDM855", tela: "AMOLED" },
     { id: 373, name: 'Xiaomi Mi 9 Pro', armazenamento: "128GB", ram: '8GB', processador: "Snapdragon 855 Plus Qualcomm SDM855", tela: "Super AMOLED" },
     { id: 374, name: 'Xiaomi Mi 9 Pro 5G', armazenamento: "128GB", ram: '8GB', processador: "Snapdragon 855 Plus Qualcomm SDM855", tela: "Super AMOLED" },
     { id: 375, name: 'Xiaomi Mi Mix Alpha', armazenamento: "512GB", ram: '12GB', processador: "Snapdragon 855 Plus Qualcomm SDM855", tela: "Flexible OLED" },
     { id: 376, name: 'Xiaomi Mi CC9 Pro', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 730G Qualcomm SDM730G", tela: "AMOLED" },
     { id: 377, name: 'Xiaomi Qin AI Pro', armazenamento: "32GB", ram: '2GB', processador: "Unisoc SC9863A", tela: "IPS LCD" },
     { id: 378, name: 'Xiaomi Mi 10 Pro', armazenamento: "256GB", ram: '8GB', processador: "Snapdragon 865 Qualcomm SDM865", tela: "AMOLED" },
     { id: 379, name: 'Xiaomi Mi 10', armazenamento: "256GB", ram: '8GB', processador: "Snapdragon 865 Qualcomm SDM865", tela: "Super AMOLED" },
     { id: 380, name: 'Xiaomi Black Shark 3 Pro', armazenamento: "256GB", ram: '8GB', processador: "Snapdragon 865 Qualcomm SDM865", tela: "AMOLED" },
     { id: 381, name: 'Xiaomi Mi Note 10 Lite', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 730G Qualcomm SDM730G", tela: "AMOLED" },
     { id: 382, name: 'Xiaomi Mi 10 Lite Zoom', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 765G Qualcomm SDM765", tela: "AMOLED" },
     { id: 383, name: 'Xiaomi Black Shark 3S', armazenamento: "256GB", ram: '12GB', processador: "Snapdragon 865 Qualcomm SDM865", tela: "AMOLED" },
     { id: 384, name: 'Xiaomi Mi 10 Ultra', armazenamento: "256GB", ram: '8GB', processador: "Snapdragon 865 Qualcomm SDM865", tela: "AMOLED" },
     { id: 385, name: 'Xiaomi Mi 10S', armazenamento: "256GB", ram: '8GB', processador: "Snapdragon 870 Qualcomm SM8250-AC", tela: "AMOLED" },
     { id: 386, name: 'Xiaomi Black Shark 4 Pro', armazenamento: "256GB", ram: '8GB', processador: "Snapdragon 888 Qualcomm SM8350", tela: "Super AMOLED" },
     { id: 387, name: 'Xiaomi Mi 11 Ultra', armazenamento: "256GB", ram: '12GB', processador: "Snapdragon 888 Qualcomm SM8350", tela: "AMOLED" },
     { id: 388, name: 'Xiaomi Black Shark 2 Pro', armazenamento: "128GB", ram: '8GB', processador: "Snapdragon 855 Plus Qualcomm SDM855", tela: "AMOLED" },
     { id: 389, name: 'Xiaomi Mi 9T Pro', armazenamento: "64GB", ram: '6GB', processador: "Snapdragon 855 Qualcomm SDM855", tela: "AMOLED" },
     { id: 390, name: 'Xiaomi Mi 9 Lite', armazenamento: "128GB", ram: '6GB', processador: "Snapdragon 710 Qualcomm SDM710", tela: "AMOLED" },
  ];
    
  module.exports = data;    